platform :ios, "8.0"

use_frameworks!

def rx_pods
    pod 'RxSwift', '~>2.4'
    pod 'RxCocoa', '~>2.4'
end

def rx_test_pods
    pod 'RxTests'
end

def rx_data_pods
    pod 'RxDataSources', '~>0.8.1'
end

def net_pods
    pod 'Alamofire'
    pod 'RxAlamofire'
    pod 'Moya'
    pod 'Moya/RxSwift'
end

def model_pods
    pod 'ObjectMapper'
end

target 'RxWhy' do
    rx_pods
end

